trigger:
  branches:
    include:
      - master  # ou ta branche de production

pool:
  vmImage: 'ubuntu-latest'

variables:
  APP_URL: 'http://localhost:3000'  # Remplace par l'URL de ton application

steps:
# 1. Pull de l'image OWASP ZAP depuis Docker Hub
- task: Docker@2
  inputs:
    command: 'pull'
    containerRegistry: 'dockerhub'  # Nom de ta connexion de service Docker
    repository: 'owasp/zap2docker-stable'
    tags: 'latest'
  displayName: 'Pull OWASP ZAP Image'

# 2. Exécuter OWASP ZAP via Docker
- script: |
    docker run --rm \
      -v $(System.DefaultWorkingDirectory):/zap/wrk/:rw \
      -e TARGET=$APP_URL \
      owasp/zap2docker-stable zap-full-scan.py -t $TARGET
  displayName: 'Run OWASP ZAP DAST Scan'
