trigger:
  branches:
    include:
      - master  # Déclenche le pipeline sur chaque push vers la branche master

pool:
  vmImage: 'ubuntu-latest'  # Utilise une image Ubuntu pour exécuter les tâches

steps:
# Installer Node.js
- task: UseNode@2
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

# Installer les dépendances de l'application
- task: npm@1
  inputs:
    command: 'install'
  displayName: 'Install dependencies'

# Exécuter les tests unitaires (s'il y en a)
- task: npm@1
  inputs:
    command: 'test'
  displayName: 'Run Tests'

# Exécuter OWASP ZAP pour des tests de sécurité dynamiques (DAST)
- task: Docker@2
  inputs:
    containerRegistry: '$(dockerRegistryServiceConnection)'  # Si tu utilises Docker Registry
    repository: 'owasp/zap2docker-stable'
    command: 'run'
    arguments: '-t http://$(APP_URL) -r zap_report.html'  # Tests de sécurité dynamiques
  displayName: 'Run OWASP ZAP DAST'

# Déployer l'application dans un environnement de test
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'AzureSubscription'  # Ton abonnement Azure
    appName: 'YourWebApp'  # Nom de ton application Azure Web App
    package: '$(System.DefaultWorkingDirectory)/_yourApp/drop'
  displayName: 'Deploy Application to Azure Web App'
